#define FRAME_RATE 144
#define MAX_FREQUENCY 300
#define MIN_FREQUENCY -300
#define WIDTH 1600
#define HEIGHT 900
#define STORAGE_THRESHOLD 20 * FRAME_RATE
#define dt 0.02 * (MAX_FREQUENCY - MIN_FREQUENCY) / MAX_FREQUENCY / FRAME_RATE